// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEa3Jwq-Gpm9D38Zjgc0wVWXDikyEDjYY',
    appId: '1:845786661216:web:bed5fce05a907d253fde05',
    messagingSenderId: '845786661216',
    projectId: 'notes-24bde',
    authDomain: 'notes-24bde.firebaseapp.com',
    storageBucket: 'notes-24bde.appspot.com',
    measurementId: 'G-LHQE6E99EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBUF9PLgd-bWDCcekfPdlriVYiqcTFSAs',
    appId: '1:845786661216:android:0ca19425a6e7c1713fde05',
    messagingSenderId: '845786661216',
    projectId: 'notes-24bde',
    storageBucket: 'notes-24bde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi3aYuUjTtUUS_CpVnamViiywtefQWThE',
    appId: '1:845786661216:ios:253c84c39895fa523fde05',
    messagingSenderId: '845786661216',
    projectId: 'notes-24bde',
    storageBucket: 'notes-24bde.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi3aYuUjTtUUS_CpVnamViiywtefQWThE',
    appId: '1:845786661216:ios:253c84c39895fa523fde05',
    messagingSenderId: '845786661216',
    projectId: 'notes-24bde',
    storageBucket: 'notes-24bde.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEa3Jwq-Gpm9D38Zjgc0wVWXDikyEDjYY',
    appId: '1:845786661216:web:b0209e0a963b909c3fde05',
    messagingSenderId: '845786661216',
    projectId: 'notes-24bde',
    authDomain: 'notes-24bde.firebaseapp.com',
    storageBucket: 'notes-24bde.appspot.com',
    measurementId: 'G-GB0GFL624X',
  );
}
